server:
  port: 80
spring:
  application:
    name: cloud-order-consumer

feign:
  client:
    config:
      default:
        # 连接超时
        connectTimeout: 2000
        # 读取数据超时时间
        readTimeout: 2000

eureka:
  instance:
    #实例名字
    instance-id: cloud-order-openfegin-consumer80
  client:
    service-url:
      # 指定eureka server地址
      #defaultZone: http://localhost:7001/eureka/
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/

# 日志增强
logging:
  level:
    # com.hp.consumer.service是openFeign接口所在的包名
    com.hp.consumer.service: debug