server:
  port: 8080
spring:
  application:
    name: order-consumer8080

eureka:
  client:
    service-url:
      # Eureka server 地址
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
