server:
  port: 8001
spring:
  application:
    name: payment-provider

eureka:
  instance:
#    自定义注册名
    instance-id: payment-provider8001

  client:
    service-url:
      # Eureka server 地址
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
management:
  endpoints:
    web:
      exposure:
        exclude: *
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

