server:
  port: 7001
eureka:
  instance:
    # eureka服务端的实例名字
    hostname: eureka7001

  client:
    #是否将自己注册到eureka server
    register-with-eureka: false

    # 表示是否从Eureka Server获取注册的服务信息
    fetch-registry: false

    # 设置与 Eureka server交互的地址查询服务和注册服务都需要依赖这个地址
    service-url:
      defaultZone: http://localhost:7002/eureka/
  server:
    # 关闭服务保护机制
    enable-self-preservation: false